---
- name: "Restart ipahealthcheck_exporter"
  ansible.builtin.service:
    name: "ipahealthcheck_exporter"
    state: "restarted"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
